services:
  bobsim: &bobsim-base
    build:
      context: .
      dockerfile: Dockerfile
    image: bobdyn/bobsim:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    network_mode: none
    environment:
      PYTHONPATH: /workspace
    stdin_open: true
    tty: true

  standard:
    <<: *bobsim-base
    working_dir: /workspace/simulations/response/mbd

  envelope:
    <<: *bobsim-base
    working_dir: /workspace/simulations/envelope

  opt:
    <<: *bobsim-base
    working_dir: /workspace/optimization

  app:
    <<: *bobsim-base
    network_mode: bridge
    init: true
    environment:
      PYTHONPATH: /workspace
      BOBSIM_OPENMODELICA_SETTINGS: openmodelica.docker.json
