services:
  bobsim: &bobsim-base
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: bobdyn/bobsim:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace
    stdin_open: true
    tty: true

  doe:
    <<: *bobsim-base
    working_dir: /workspace/_4_DOE