from __future__ import annotations

from pathlib import Path

from _0_Utils import config_io


APP_ROOT = Path("_5_App")
STATIC_ROOT = APP_ROOT / "static"

USER_DATA_ROOT = APP_ROOT / "user_data"
USER_CONFIG_ROOT = USER_DATA_ROOT / "config"
USER_CACHE_ROOT = USER_DATA_ROOT / "cache"
USER_RESULTS_ROOT = USER_DATA_ROOT / "results"
USER_WORKSPACE_ROOT = USER_DATA_ROOT / "workspaces"

SETTINGS_ROOT = USER_CONFIG_ROOT / "app"
SAVED_VEHICLE_ROOT = USER_CONFIG_ROOT / "vehicles"
SAVED_SIM_CONFIG_ROOT = USER_CONFIG_ROOT / "simulations"
SAVED_RESULTS_ROOT = USER_RESULTS_ROOT / "saved"
VEHICLE_WORKSPACE_ROOT = USER_WORKSPACE_ROOT / "vehicles"
BUILD_ARCHIVE_ROOT = USER_CACHE_ROOT
MODELICA_BUILD_CACHE_ROOT = BUILD_ARCHIVE_ROOT / "modelica"

ACTIVE_SIM_CONFIG_ROOT = config_io.ACTIVE_CONFIG_ROOT
# Pristine snapshot for configs that are still edited in place, so "Default"
# keeps working for them without a second copy in the repo.
DEFAULT_SNAPSHOT_ROOT = USER_CONFIG_ROOT / "defaults"
OPENMODELICA_SETTINGS_PATH = SETTINGS_ROOT / "openmodelica.json"
RUNTIME_SEED_MANIFEST_PATH = SETTINGS_ROOT / "runtime_seed.json"

USER_DATA_DIRS = (
    SETTINGS_ROOT,
    SAVED_VEHICLE_ROOT,
    SAVED_SIM_CONFIG_ROOT,
    SAVED_RESULTS_ROOT,
    VEHICLE_WORKSPACE_ROOT,
    MODELICA_BUILD_CACHE_ROOT,
    ACTIVE_SIM_CONFIG_ROOT,
    DEFAULT_SNAPSHOT_ROOT,
)
